### ISSUE TITLE
Add Luke Campbell to repository

### ISSUE THREAD

**Issue by robragsdale** [ioos/qartod#7]
@ioos/owners @emiliom need to add @LukeCampbell to the QARTOD repository.  I do not have the rights to add people.  Once before, @emiliom had to add someone for me.  What do I need to do gain rights to add people to this and other repositories?

**Comment by emiliom** [comment]
@robragsdale, today I was trying to add @lukecampbell to this repo. My understanding is that the way to do this is by adding him as a member of the [ioos qartod team](https://github.com/orgs/ioos/teams/qartod), but [based on the github instructions I was following](https://help.github.com/articles/adding-people-to-teams-in-an-organization/), it looks to me like I don't have rights to modify the team.

Can you look into it? In response to your question, I thought you and I had the same top-level admin rights to the ioos organization. I thought you had created the qartod repo, though Derrick is listed as the owner of the [qartod team](https://github.com/orgs/ioos/teams/qartod). Thanks.

**Comment by robragsdale** [comment]
@emiliom I did the create the qartod repo and that is/was permissible as a member under the IOOS organization.  It looks like github did [reorg of their member privileges](https://github.com/orgs/ioos/people?page=1).  Under this reorg, owners or team maintainers, who can be designated by owners can add members to a team.  Currently, @dpsnowden @rsignell-usgs and @duncombe are the owners of the IOOS organization.  I do not have the permissions either to add members to a team.  

@dpsnowden can you [give me team maintainer permissions](https://help.github.com/articles/giving-team-maintainer-permissions-to-an-organization-member/) that will give me more permissions for managing the IOOS github repositories and teams?

**Comment by emiliom** [comment]
Thanks for figuring that out, Rob. It looks like @lukecampbell can request to be added to a team, but someone would still need to approve it; so it'll be good for you to have ioos org/team admin rights.

**Comment by robragsdale** [comment]
@dpsnowden can you make me a team maintainer? [Instructions for promoting an organization member to team maintainer](https://help.github.com/articles/giving-team-maintainer-permissions-to-an-organization-member/).

**Comment by emii** [comment]
Sorry, something might have gone wrong, I am getting notifications from this thread directly to my email, can you please verify your configurations?, Thanks

**Comment by robragsdale** [comment]
Sorry@emil meant @emiliom in my initial thread.

**Comment by emiliom** [comment]
@robragsdale and @lukecampbell, whatever happened to this request? Was Luke added to the team? The repo is looking mighty empty ...

**Comment by lukecampbell** [comment]
I still haven't been added.

**Comment by robragsdale** [comment]
Luke, you are in the list of the QARTOD repository team members.  https://github.com/orgs/ioos/teams/qartod

Can you check if you can make edits or changes to the repository?

**Comment by lukecampbell** [comment]
That's affirmative, I'm on that team but that team doesn't have privileges to administer this repository. 

I am just a collaborator at this point, I can't review and merge changes, make administrative changes or edit releases.

**Comment by robragsdale** [comment]
@lukecampbell I updated your status to 'team maintainer' that gives you more permissions than a collaborator.  If there is still some change that you cannot make, we may have to make you an 'organization member'.  I think owners can only make that change.

**Comment by lukecampbell** [comment]
I still don't have access. Specifically write access.

**Comment by robragsdale** [comment]
@lukecampbell Thanks for the feedback.  I am trying to figure out how to get you the read/write permissions.  I also am not the owner of the qartod repository, only a team maintainer, which I think is limiting to what permissions I can give.

**Comment by robragsdale** [comment]
I researched permissions more and emailed github.  I found out the team maintainer role does not give me the write access I need to resolve an outstanding PR or give a team member write access to a repository.  I am currently just a ['team maintainer'](https://help.github.com/articles/giving-team-maintainer-permissions-to-an-organization-member/) so think that I need to [organizer permissions] (https://help.github.com/articles/changing-a-person-s-role-to-owner/).  There are three owners to the IOOS repository: @dpsnowden , @rsignell-usgs , and @ocefpaf .  Could I be granted an [organizer role](https://help.github.com/articles/changing-a-person-s-role-to-owner/).     

Email exchange with github: 

That's correct. A team maintainer can not grant the team write access to a repository.

Cheers,
John


> John,
>
> So an organization admin is the same as an owner. A team maintainer cannot
> give a team write access to the repository? Is that correct?
>
> Thanks, again,
> Rob

Hi Rob,

The team maintainer's abilities are detailed here:

https://help.github.com/articles/giving-team-maintainer-permissions-to-an-organization-member/

As a team admin you can add existing members of the organization to the team and, as long as the team already has write access to the repository in question, the new team member will gain the abilities you're looking for.

If the user you want to add is not already an organization member, or the team doesn't already have write access to the repository, then an organization admin would have to make those changes first.

Let us know if you need any further help.

Cheers,
John

**Comment by robragsdale** [comment]
Filipe gave me owner access.  Thanks Filipe!

**Comment by emiliom** [comment]
Thanks, @ocefpaf and @robragsdale !

**Comment by lukecampbell** [comment]
I still don't have write privileges for this repo.

**Comment by robragsdale** [comment]
@lukecampbell you have admin rights now to the qartod repository.

**Comment by lukecampbell** [comment]
I certainly do.
